{% set name = "langgraph-checkpoint-aws" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langgraph_checkpoint_aws-{{ version }}.tar.gz
  sha256: a97350ae5885b67de2a59841c4d3e8c50f088afcee41668366a499979c680e69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - langgraph-checkpoint >=3.0.0,<4.0.0
    - langgraph >=1.0.0
    - boto3 >=1.40.19
    - typing_extensions >=4.0.0

test:
  imports:
    - langgraph_checkpoint_aws
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: A LangChain checkpointer implementation that uses Bedrock Session Management Service to enable stateful and resumable LangGraph agents.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - michaelnchin
    - ccurme
